# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'
  functionAppName: 'mthcricket01api'
  serviceNamespace: 'Mth.Darts.Cricket'
  system.debug: true

steps:
- script: dotnet --version
  displayName: 'Get agent dotnet version'
# - task: DotNetCoreInstaller@0
#   inputs:
#     version: '2.2.101'
- script: dotnet build '$(serviceNamespace)' --configuration $(buildConfiguration)
  displayName: 'Build Service (Class Library)'
- script: dotnet build '$(serviceNamespace).Tests' --configuration $(buildConfiguration)
  displayName: 'Build Service tests'
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(serviceNamespace).Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  displayName: 'Test Service'
- script: dotnet build '$(serviceNamespace).Api' --configuration $(buildConfiguration)
  displayName: 'Build API (Azure Function App)'
- script: dotnet build '$(serviceNamespace).Api.Tests' --configuration $(buildConfiguration)
  displayName: 'Build API tests'
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '$(serviceNamespace).Api.Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
  displayName: 'Test API'
- script: dotnet publish '$(serviceNamespace).Api' --output '../FunctionApp'
  displayName: 'Prepare Build artifacts'
# https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/ArchiveFilesV2/task.json
- task: ArchiveFiles@2
  inputs: 
    rootFolderOrFile: 'FunctionApp'
    includeRootFolder: true # https://docs.microsoft.com/en-us/azure/azure-functions/functions-continuous-deployment#continuous-deployment-requirements
    archiveType: zip
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip' # Default, but clearer to include here anyway
    replaceExistingArchive: true
  displayName: 'Zip up function app artifacts'
# https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/CopyFilesV2/task.json
- task: CopyFiles@2
  inputs:
    Contents: 'FunctionApp/**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/FunctionApp'
  displayName: 'Copy published API files'
- task: CopyFiles@2
  inputs:
    Contents: 'azuredeploy.json'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
  displayName: 'Copy ARM template files'
# https://github.com/Microsoft/azure-pipelines-tasks/blob/master/Tasks/PublishBuildArtifactsV1/task.json
# To be replaced by PublishPipelineArtifact early 2019
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: '$(Build.ArtifactStagingDirectory)'
    artifactName: 'drop' # 1 drop artifact should contain both the functionapp and the ARM template
    artifactType: 'Container' # For Linux agent File Share is not supported
    TargetPath: '$(System.ArtifactsDirectory)'
  displayName: 'Publish Build artifacts'
# https://github.com/Microsoft/azure-pipelines-tasks/tree/master/Tasks/PublishPipelineArtifactV0
# - task: PublishPipelineArtifact@0
#   inputs:
#     artifactName: '$(functionAppName)'
#     targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'