# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

variables:
  buildConfiguration: 'Release'

steps:
- script: dotnet build .\Mth.Darts.Cricket\ --configuration $(buildConfiguration)
  displayName: 'Build Cricket library'
- script: dotnet build .\Mth.Darts.Cricket.Tests\ --configuration $(buildConfiguration)
  displayName: 'Build Cricket library tests'
- script: dotnet test .\Mth.Darts.Cricket.Tests\
  displayName: 'Run unit tests (xUnit)'
- script: dotnet build .\Mth.Darts.Cricket.Api\ --configuration $(buildConfiguration)
  displayName: 'Build Cricket API (Azure Function App)'
